### ISSUE TITLE
horizontalDischarge and verticalDischarge

### ISSUE THREAD

**Issue by jbensabat** [lanl/nuflood#4]
Hi 
I have started running the code and I have a question regarding the output
what do you mean by horizontal and vertical discharges ? Is it in the x and y directions of the plane or in the plane and in the vertical direction (z) ?
thanks 
jac

**Comment by tasseff** [comment]
These are discharges in the two horizontal dimensions (x and y).

**Comment by jbensabat** [comment]
Thanks
Jac

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
